#ifndef NFS_RACING_SURFACES_INCLUDED
#define NFS_RACING_SURFACES_INCLUDED

// Geometry, lighting, shadows, motion vectors and render passes are generated by HDRP Shader Graph.
// Only pipeline-independent surface evaluation lives here.
float _RacingWetness;
float _RacingStandingWater;
float _RacingWeatherTime;
float _RacingRainIntensity;
float _RacingRainRipples;
float _RacingRainSpots;
float4 _RacingWindDirection;
float _RacingWindSpeed;

float RacingHash(float2 p) { return frac(sin(dot(p,float2(127.1,311.7)))*43758.5453); }
float RacingNoise(float2 p)
{
    float2 i=floor(p),f=frac(p);f=f*f*(3-2*f);
    return lerp(lerp(RacingHash(i),RacingHash(i+float2(1,0)),f.x),lerp(RacingHash(i+float2(0,1)),RacingHash(i+1),f.x),f.y);
}
float RacingRainRing(float2 p,float time,float seed)
{
    float2 cell=floor(p);
    float2 local=frac(p);
    float2 centre=float2(
        RacingHash(cell+float2(17.3+seed,4.7)),
        RacingHash(cell+float2(3.1,29.9+seed)))*.6+.2;
    float age=frac(time+RacingHash(cell+seed)*.93);
    float radius=age*.48;
    float ring=1-smoothstep(.018,.055,abs(length(local-centre)-radius));
    float selected=step(.56,RacingHash(cell+float2(41.7,11.2+seed)));
    return ring*selected*(1-age)*(1-age);
}
float3 RacingNormal(UnityTexture2D map,float2 uv,float strength)
{
    float3 n=UnpackNormal(map.tex.Sample(map.samplerstate,uv));
    return normalize(lerp(float3(0,0,1),n,saturate(strength)));
}
void Grime_float(float2 UV,float4 VertexColor,float3 PositionWS,
    UnityTexture2D BaseMap,UnityTexture2D BumpMap,float4 BaseColor,float4 EmissionColor,
    float Smoothness,float Metallic,float NormalStrength,float Falloff,float Pattern,float FadeStart,float FadeEnd,
    out float3 Color,out float3 NormalTS,out float Metal,out float Smooth,out float AO,out float3 Emission,out float Alpha)
{
    float4 base=BaseMap.tex.Sample(BaseMap.samplerstate,UV)*BaseColor;
    float edge=min(min(UV.x,1-UV.x),min(UV.y,1-UV.y));float opacity=smoothstep(0,max(.001,Falloff*.5),edge);
    float grit=RacingHash(floor(UV*60));float wave=sin(UV.y*35)*.025+sin(UV.y*79)*.012;
    if(Pattern>.5&&Pattern<1.5)opacity*=lerp(.25,1,grit)*(1-smoothstep(.1,.55,length(UV-.5)));
    else if(Pattern>1.5&&Pattern<2.5)opacity*=1-smoothstep(.008,.025,abs(UV.x-.5-wave));
    else if(Pattern>2.5&&Pattern<3.5)opacity*=lerp(.7,1,grit);
    else if(Pattern>3.5&&Pattern<4.5)opacity*=smoothstep(.15,.3,abs(UV.x-.5))*(.65+.35*grit);
    else if(Pattern>4.5&&Pattern<5.5)opacity*=(1-smoothstep(.2,.5,length((UV-.5)*float2(1,1.2))))*lerp(.8,1,grit);
    else if(Pattern>5.5&&Pattern<6.5)opacity*=step(.4,sin(UV.x*28+sin(UV.y*20)*3))*(1-smoothstep(.35,.5,abs(UV.y-.5)));
    else if(Pattern>6.5&&Pattern<7.5)opacity*=1-smoothstep(.25,.5,length(UV-.5)+sin(UV.x*30)*.04);
    else if(Pattern>7.5)opacity*=lerp(.2,1,grit)*(1-smoothstep(.25,.5,abs(UV.x-.5)));
    #if !defined(SHADERGRAPH_PREVIEW)
    opacity*=saturate((FadeEnd-distance(_WorldSpaceCameraPos,PositionWS))/max(.01,FadeEnd-FadeStart));
    #endif
    Color=base.rgb;NormalTS=RacingNormal(BumpMap,UV,NormalStrength);Metal=Metallic;Smooth=Smoothness;AO=1;Emission=EmissionColor.rgb;
    Alpha=saturate(opacity*base.a*VertexColor.a);
}
void GrimeMultiply_float(float2 UV,float4 VertexColor,float3 PositionWS,
    UnityTexture2D BaseMap,UnityTexture2D BumpMap,float4 BaseColor,float4 EmissionColor,
    float Smoothness,float Metallic,float NormalStrength,float Falloff,float Pattern,float FadeStart,float FadeEnd,
    out float3 Color,out float Alpha)
{
    float3 n,e;float m,s,ao,a;
    Grime_float(UV,VertexColor,PositionWS,BaseMap,BumpMap,BaseColor,EmissionColor,Smoothness,Metallic,NormalStrength,Falloff,Pattern,FadeStart,FadeEnd,Color,n,m,s,ao,e,a);
    // Multiplication modulates already-lit substrate color, avoiding a second lighting response on the stain.
    Color=lerp(1,saturate(Color),a);Alpha=1;
}
void Skid_float(float2 UV,float4 VertexColor,float3 PositionWS,out float3 Color,out float Alpha)
{
    Color=VertexColor.rgb;Alpha=VertexColor.a*saturate(min(UV.x,1-UV.x)*12);
}
void Particles_float(float2 UV,float4 VertexColor,float3 PositionWS,out float3 Color,out float3 NormalTS,out float Metal,out float Smooth,out float AO,out float3 Emission,out float Alpha)
{
    Color=VertexColor.rgb;NormalTS=float3(0,0,1);Metal=0;Smooth=.1;AO=1;Emission=0;
    // A soft radial falloff replaces visible billboard squares without changing particle simulation or budgets.
    Alpha=VertexColor.a*(1-smoothstep(.1,.5,length(UV-.5)));
}
void Road_float(float2 UV,float4 VertexColor,float3 PositionWS,UnityTexture2D BaseColorMap,UnityTexture2D NormalMap,UnityTexture2D MaskMap,
    float4 BaseColor,float Smoothness,float Metallic,float NormalScale,float Tiling,float Wetness,float PuddleCoverage,
    out float3 Color,out float3 NormalTS,out float Metal,out float Smooth,out float AO,out float3 Emission,out float Alpha)
{
    float2 uv=PositionWS.xz*Tiling;float4 mask=MaskMap.tex.Sample(MaskMap.samplerstate,uv);
    // Keep the wet film continuous while breaking standing water into broad,
    // irregular patches. Rotating the sampling domain avoids conspicuous
    // horizontal bands on a long straight road.
    float2 p=PositionWS.xz;
    float2 rotated=float2(p.x*.94-p.y*.34,p.x*.34+p.y*.94);
    float macro=RacingNoise(rotated*float2(.17,.11)+float2(12.3,-5.1));
    float breakup=RacingNoise(rotated*float2(.41,.28)-float2(3.7,8.2));
    float aggregate=RacingNoise(rotated*1.8+float2(6.1,2.7));
    float broad=macro*.58+breakup*.3+aggregate*.12;
    float wet=saturate(max(Wetness,_RacingWetness));
    float film=saturate(wet*.36+_RacingStandingWater*.12);
    float accumulation=smoothstep(.56,.78,1-broad)*saturate(PuddleCoverage*1.15);
    float puddle=accumulation*saturate(wet*.78+_RacingStandingWater*.3);
    float water=saturate(film+puddle*.75);
    float damp=saturate(wet*.55+film*.3+aggregate*.15);damp*=wet;
    Color=BaseColorMap.tex.Sample(BaseColorMap.samplerstate,uv).rgb*BaseColor.rgb;
    // A wet asphalt film darkens the aggregate without crushing all of its
    // texture. The lower albedo is what lets the clear coat/reflection read.
    Color*=lerp(1,.8,damp)*lerp(.96,1.04,aggregate);
    NormalTS=RacingNormal(NormalMap,uv,NormalScale);
    float2 wind=normalize(_RacingWindDirection.xz+float2(.0001,.0002));
    float2 crossWind=float2(-wind.y,wind.x);
    // Two decorrelated grids form brief expanding rings. Their strength is
    // supplied by WeatherSurfaceCoverage, so dry roads and low tiers do not pay
    // for a visually active rain surface.
    float ringA=RacingRainRing(rotated*1.7+wind*_RacingWeatherTime*.015,_RacingWeatherTime*.72,0);
    float ringB=RacingRainRing(rotated*2.3-crossWind*_RacingWeatherTime*.01,_RacingWeatherTime*.91,13.7);
    float ripple=(ringA-ringB*.65)*_RacingRainRipples*saturate(puddle*.9+film*.15);
    float spotNoise=RacingNoise(rotated*7.2+floor(_RacingWeatherTime*7)*.031);
    float spots=smoothstep(.82,.98,spotNoise)*_RacingRainSpots*saturate(film+puddle);
    NormalTS=normalize(lerp(NormalTS,float3(ripple*.035+spots*.012,-ripple*.024,1),saturate(water*.32)));
    Metal=Metallic*mask.r*(1-water*.65);AO=mask.g;
    Smooth=lerp(saturate(Smoothness*mask.a),.82,film);Smooth=lerp(Smooth,.975,puddle);
    // HDRP reflection probes/SSR do the primary reflection work. A restrained
    // grazing highlight keeps the wet road readable in the small demo scene
    // even when no probe has a useful capture yet.
    float3 viewDirection=normalize(_WorldSpaceCameraPos-PositionWS);
    float grazing=1-saturate(abs(viewDirection.y));
    float fresnel=pow(grazing,4);
    float movingHighlight=saturate(.45+ringA*.4+spots*.35);
    float sheen=film*.08+puddle*(.12+.2*movingHighlight)+puddle*.18*fresnel;
    Emission=float3(.06,.085,.12)*sheen*_RacingRainIntensity;
    Alpha=1;
}
#endif
