"""Build a local visual inventory without changing texture pixels."""
from decode_ui import *
manifest=json.loads((OUT/'manifest.json').read_text())
def category(t):
    n=t['name'];source=t['source']
    if re.search(r'^(SKY_|CAREER_[XYZ](NEG|POS)|CSHOP_[XYZ](NEG|POS)|CARLOT_[XYZ](NEG|POS)|QRACE_[XYZ](NEG|POS))|ENVMAP|ENVIRONMEN|REFLECTION',n):return 'Shared world textures'
    if n.startswith(('FONT_','TAC_NUMBERS','CONDUIT')):return 'Bitmap fonts'
    if n.startswith(('RIVAL_','TIP_')):return 'Portraits and tutorials'
    if re.search(r'LOGO|BRAND|_ICON$',n) and re.search(r'LOGO|BRAND|AEM|CASTROL|BREMBO|KONI|BBS|ENKEI|5ZIGEN|HKS|APEX',n):return 'Brands and logos'
    if re.search(r'^(BUSTED_|EVADED_|IMPOUND|DEFEATED_)',n):return 'Status lettering'
    if 'HUD' in source.upper() or re.search(r'METER|RADAR|RPM|NEEDLE|REDLINE|PURSUIT_|DRAG_|TACH|NITROUS',n):return 'HUD and gauges'
    if re.search(r'ICON|MARKER|_ARROW|ARROW_|BUTTON|PC_|_KEY|VISUAL_PART|PERFORMANCE_|VINYL_GROUP|LANGSELECT|MODE_',n):return 'Icons and controls'
    if re.search(r'GRIT|GRUNGE|SPLAT|VIGNETTE|VINETTE|UNDERLAY|BACKING|BORDER|MASK|PANEL|GREY|WHITE|CIRCLE|SQUARE',n):return 'Panels and textures'
    return 'Other decoded graphics'
entries=[]
for t in manifest['textures']:
    entries.append({k:t[k] for k in ('name','nameHash','width','height','path','sources','alphaExtrema','pngSha256')})
    entries[-1].update(category=category(t),status='Awaiting redraw')
(OUT/'catalog.json').write_text(json.dumps(entries,indent=2)+'\n')
page=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Most Wanted · UI asset library</title><style>
*{box-sizing:border-box}body{margin:0;background:#121416;color:#f2f2ed;font:14px -apple-system,BlinkMacSystemFont,sans-serif}header{padding:28px 32px 22px;border-bottom:1px solid #36393a;position:sticky;top:0;background:#121416f2;backdrop-filter:blur(12px);z-index:2}h1{font-size:25px;letter-spacing:-.8px;margin:0 0 8px}p{color:#a9aca9;margin:8px 0}strong{color:#deef84}nav{display:flex;gap:12px;margin-top:20px;align-items:center}input,select,button{font:inherit;color:inherit;background:#222627;border:1px solid #454a4b;border-radius:6px;padding:10px 12px}input{width:320px}button{cursor:pointer}#count{margin-left:auto}main{padding:24px 32px;display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:16px}article{min-width:0;border:1px solid #373b3c;background:#1b1e20;border-radius:6px;overflow:hidden;cursor:pointer}article:hover{border-color:#deef84}.art{height:175px;display:flex;align-items:center;justify-content:center;background:repeating-conic-gradient(#292c2e 0% 25%,#333739 0% 50%) 50%/24px 24px}.art img{max-width:90%;max-height:90%;object-fit:contain}article .info{padding:13px}h2{font-size:11px;line-height:1.5;overflow-wrap:anywhere;margin:0 0 7px}small{color:#a9aca9;font-size:11px}dialog{color:inherit;background:#1b1e20;border:1px solid #616764;border-radius:10px;padding:24px;width:90vw;max-width:1000px}dialog::backdrop{background:#000c}.detail{display:grid;grid-template-columns:1fr 300px;gap:24px}.detail .art{height:65vh}.detail img{max-width:100%;max-height:100%}pre{white-space:pre-wrap;word-break:break-word;font:12px monospace;color:#b8bfbc}a{color:#deef84}#close{float:right;margin-bottom:15px}@media(max-width:650px){header,main{padding:18px}.detail{display:block}.detail .art{height:45vh}nav{flex-wrap:wrap}input{width:100%}#count{margin:0}}
</style><header><h1>Most Wanted <span style="color:#deef84">/</span> UI asset library</h1><p>Original decoding · 1,387 records · <strong>1,119 unique textures</strong> · 57 archives scanned</p><p>Remake in progress. Generated drafts have not passed production checks.</p><nav><input id="search" type="search" placeholder="Search asset names, hashes, or archives" aria-label="Search assets"><select id="category" aria-label="Asset category"><option value="">All categories</option></select><button id="background">Dark backdrop</button><span id="count"></span></nav></header><main id="grid"></main><dialog id="dialog"><button id="close">Close</button><div class="detail"><div class="art"><img id="detailImage" alt=""></div><section><h2 id="title"></h2><pre id="metadata"></pre><a id="download" download>Open original PNG</a></section></div></dialog><script>
const assets=DATA;const grid=document.querySelector('#grid'),search=document.querySelector('#search'),category=document.querySelector('#category'),dialog=document.querySelector('#dialog');
for(const c of [...new Set(assets.map(a=>a.category))].sort()){const o=document.createElement('option');o.value=c;o.textContent=c;category.append(o)}
function url(a){return a.path.replace(/^Art\/UI\//,'')}
function openAsset(a){document.querySelector('#detailImage').src=url(a);document.querySelector('#detailImage').alt=a.name;document.querySelector('#title').textContent=a.name;document.querySelector('#metadata').textContent=`${a.width} × ${a.height} pixels\nHash: ${a.nameHash}\nAlpha: ${a.alphaExtrema.join('–')}\n\n${a.category}\n${a.status}\n\nSources\n${a.sources.join('\n')}\n\nSHA-256\n${a.pngSha256}`;document.querySelector('#download').href=url(a);dialog.showModal()}
function render(){const q=search.value.toLowerCase();const list=assets.filter(a=>(!category.value||a.category===category.value)&&(!q||[a.name,a.nameHash,...a.sources].join(' ').toLowerCase().includes(q)));document.querySelector('#count').textContent=`${list.length} assets`;grid.replaceChildren();for(const a of list){const card=document.createElement('article');card.tabIndex=0;card.setAttribute('aria-label',a.name);const art=document.createElement('div');art.className='art';const image=document.createElement('img');image.loading='lazy';image.src=url(a);image.alt=a.name;art.append(image);const info=document.createElement('div');info.className='info';const title=document.createElement('h2');title.textContent=a.name;const details=document.createElement('small');details.textContent=`${a.width} × ${a.height} · ${a.nameHash}`;info.append(title,details);card.append(art,info);card.onclick=()=>openAsset(a);card.onkeydown=e=>{if(e.key==='Enter')openAsset(a)};grid.append(card)}}search.oninput=render;category.onchange=render;document.querySelector('#close').onclick=()=>dialog.close();let dark=false;document.querySelector('#background').onclick=()=>{dark=!dark;document.querySelector('#backdropStyle').textContent=dark?'.art{background:#101214}':''};render();
</script><style id="backdropStyle"></style></html>'''
(PROJECT/'Art/UI/index.html').write_text(page.replace('DATA',json.dumps(entries).replace('</','<\\/')))
print(dict(collections.Counter(e['category'] for e in entries)))
